### ISSUE TITLE
Themes based on all of the Solarized accent colors

### ISSUE THREAD

**Issue by treymerkley** [Ferdi265/numix-solarized-gtk-theme#16]
I figured I'd fork this and build it myself since the last update (apparently) made it so gobsmackingly simple to add in new colors. 

It looks like all that would be needed is to edit all of the light and dark base theme .color files and replace the existing colors with the rest, change the name to the color, commit, and then we have the solarized rainbow, right?

EDIT: Pull request merged, my goal is complete.

**Comment by Ferdi265** [comment]
Correct!

Build times are a little slow, since the build process includes generating all of the images with inkscape, but as for the color changes, that's easy now.

Have fun experimenting :)

**Comment by Ferdi265** [comment]
If you'd like you can try it out and submit a pull-request. I'd be happy to merge it.

**Comment by treymerkley** [comment]
Thanks! I'll commit it in a couple of days. I also added some screenshots, if you want to use them to fix #13.

**Comment by Ferdi265** [comment]
Thanks :) I _am_ thinking about updating the Numix Readme to contain a NumixSolarized header, with information specific to this fork. We can then add screenshots there :)

Also: what Window manager / desktop environment do you use? Maybe it's time we tackle the WM-integration problem (all the WM-themes look ugly because they are unchanged at the moment)

The end result will probably be only more @@WM_COLOR_KEYS@@, so everything stays customizable.

**Comment by treymerkley** [comment]
Makes sense to me. I run XFCE, so most everything runs for me, except for a couple of little decorations that aren't themed, which is to be expected. 

Could we find more specifics in other Numix forks and port them over?
