### ISSUE TITLE
Troubles in Unity

### ISSUE THREAD

**Issue by iron-cherep** [Ferdi265/numix-solarized-gtk-theme#5]
Both first and last releases of theme don't work properly on Unity and Ubuntu 16.04. Installed them manually following instructions. Reinstalled few times and still got the same result:
![numix-solarized-unity](https://cloud.githubusercontent.com/assets/18402060/19005973/15dd3a98-8766-11e6-8486-0c29bfc25e19.png)
#

**Comment by Ferdi265** [comment]
I haven't tested it in Unity yet. As I can see the icons in the unity Top bar use a light color, which looks bad on the light numix-solarized background color. As I've said in issue #1, I plan on checking what doesn't work in the different DEs and update that accordingly. I just didn't have time for that until now.

Is there anything else that doesn't work in Unity? In your screenshot I can only identify the color.

Can you show me how it looks with standard Numix? because that's what this is based on. If not I'll look at it myself, but that will take a while

**Comment by iron-cherep** [comment]
I've only noticed problem with colors. Besides it's not current version of theme, but one of earlier releases - last one gives error message after "sudo make install" (in addition here you can see how original numix theme looks in unity):

![2016-10-03 00-47-46](https://cloud.githubusercontent.com/assets/18402060/19024020/e69b5b26-8903-11e6-8bd9-885e4f9c537f.png)

**Comment by Ferdi265** [comment]
Ahh, yes. That's because my Makefile uses bashisms, and /bin/sh is not bash on Debian on Ubuntu. I'll fix that shortly.

For now you can just try to download the theme archive [here](https://github.com/Ferdi265/numix-solarized-gtk-theme/releases/download/20160919/NumixSolarized-20160919.tar.gz). This is what you get after running `make install`. Just copy it to `/usr/share/themes` to install.

Note that this still doesn't fix the icon colors on Unity, but that will come soon-ish. (I have a lot of IRL stuff on my hands at the moment. I'll try to find time)

**Comment by iron-cherep** [comment]
Reainstalled manually from archive and now get it well working, thank you for your attention :) Light and dark themes looks like this (used numix-light icons with light theme this time):
![dark](https://cloud.githubusercontent.com/assets/18402060/19034528/991d963e-896c-11e6-9b8f-2bd86efa34b9.png)
![lignt](https://cloud.githubusercontent.com/assets/18402060/19034529/9936322a-896c-11e6-96e9-a6d14d6f19ef.png)

**Comment by Ferdi265** [comment]
Sure thing.

It seems I now have more time on my hands than expected. I'm closing this issue as further developments on Unity- or other WM-specific tweaks should be discussed in #1.
