### ISSUE TITLE
White window buttons (close, minimize ..) in solarized light theme

### ISSUE THREAD

**Issue by fabianWrede** [Ferdi265/numix-solarized-gtk-theme#9]
Hi,
I just installed the theme on Ubuntu 16.04 with Unity and noticed that the window buttons, i.e., close, minimize, etc., are white for both the dark and the light theme.
For the dark theme that is fine, but for the light theme it is not really possible to see the buttons on the light solarized background. 
Is there a way to change the color? 
Thank you

**Comment by Ferdi265** [comment]
I haven't looked much into the color of window buttons in the theme, because I use a window manager that doesn't have any.

It seems the right place to look would be the wm-integration folders, so in your case, the files in `src/unity/`.

There are tons of SVGs in there for window buttons and other Unity-related functionality. You can edit them with a simple text editor and change the colors, but IMO best way to change them is to look for what their color is now and replace them via `sed` or similar.

I was also thinking about creating a build-script that can insert color-configuration this way automatically, but that will have to wait until my next merge of numix upstream, as that is long overdue. (Due to the release of Gtk 3.22 and stuff like that).

For now I think it would be best if you locally changed to colors to your liking. Once my build script color configuration thing is complete, I can think about including your changes in the default light theme, or adding a build option.

I'd best leave this issue open as a TODO-marker so I see it when I work on it.

As you might see, I'm not very active, especially now that I sink all my time into playing the new Zelda on my Nintendo Switch (lol)

**Comment by Ferdi265** [comment]
Cannot reproduce for Ubuntu 20.04 (see screenshot images in the new README). If you are still using 16.04 (or another affected version) and still using this theme, I'll look into it, otherwise I see this as "fixed".
